import { Dashboard } from "@/components/Dashboard";
import { Header } from "@/components/Header";
import { useUserContext } from "@/context/UserContext";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const router = useRouter();
  const { user, setUser } = useUserContext();

  useEffect(() => {
    const userName = router.query.user as string;

    if (userName) {
      setUser({ ...user, username: userName });
    } else if (router.isReady && user.username === "") {
      router.replace("/login");
    }
  }, [router.query.user, router.isReady]);

  return (
    <>
      <Head>
        <title>Supera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Dashboard />
    </>
  );
}
